name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            platform: mac
          - os: windows-latest
            platform: win
          - os: ubuntu-latest
            platform: linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build TUI
      run: cd src/tui && npm ci && npm run build

    - name: Build Electron app
      run: npm run build

    - name: Build distribution
      run: |
        if [ "${{ matrix.platform }}" = "mac" ]; then
          npm run dist:mac
        elif [ "${{ matrix.platform }}" = "win" ]; then
          npm run dist:win
        elif [ "${{ matrix.platform }}" = "linux" ]; then
          npm run dist:linux
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.platform }}
        path: dist-electron/

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist-mac/*.dmg
          dist-mac/*.zip
          dist-win/*.exe
          dist-win/*.zip
          dist-linux/*.AppImage
          dist-linux/*.deb
          dist-linux/*.rpm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

